name: Lifis
version: '${version}'
main: org.jadestudios.plugins.lifis.Lifis
api-version: 1.17

commands:
  reset:
    permission: lifis.reset
  reloadconfig:
    permission: lifis.reloadconfig
  revive:
